### ISSUE TITLE
Where is fsd_common_msgs in ROS (noetic)?

### ISSUE THREAD

**Issue by avBuffer** [4399chen/Yolov8-seg-TensorRT-ROS-Jetson#1]
Where is fsd_common_msgs in ROS (noetic)? TKS!

**Comment by 4399chen** [comment]
不好意思，这是我自定义的msgs，在后续的更新中我将取消掉fsd_common_msgs并使用vision_msgs进行替代

https://github.com/ros-perception/vision_msgs/tree/noetic-devel

**Comment by 4399chen** [comment]
已经将fsd_common_msgs取消并使用vision_msgs进行替代
